---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: qwen3-4b
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: "true"
    networking.kserve.io/visibility: exposed
  name: qwen3-4b
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      args:
      - --max-model-len=8196
      - --enable-auto-tool-choice
      - --tool-call-parser=hermes
      - --gpu-memory-utilization=0.4
      env:
      - name: VLLM_CPU_KVCACHE_SPACE
        value: "12"
      resources:
        limits:
          cpu: "32"
          memory: 40Gi
        requests:
          cpu: "32"
          memory: 40Gi
      runtime: vllm-cpu-runtime
      storageUri: hf://Qwen/Qwen3-4B-Instruct-2507
    timeout: 900
