---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: guardrails-detector-ibm-hap
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: "true"
  name: guardrails-detector-ibm-hap
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: guardrails-detector-hf-runtime
      name: ""
      resources:
        limits:
          cpu: "8"
          memory: 10Gi
        requests:
          cpu: "4"
          memory: 8Gi
      runtime: guardrails-detector-huggingface-runtime
      storage:
        key: s3-creds
        path: models/granite-guardian-hap-125m
