apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    modelFormat: vLLM
    opendatahub.io/connection-path: models/granite-embedding-125m-english
    opendatahub.io/connections: odh-bucket
    opendatahub.io/model-type: generative
    openshift.io/display-name: granite-embeddings
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: Standard
    serving.kserve.io/stop: "false"
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
  name: granite-embeddings
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: RollingUpdate
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
      - --hf-overrides
      - '{"is_matryoshka":true,"matryoshka_dimensions":[768]}'
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "8"
          memory: 16Gi
        requests:
          cpu: "8"
          memory: 16Gi
      runtime: vllm-cpu-runtime
      storage:
        key: odh-bucket
        path: models/granite-embedding-125m-english
    serviceAccountName: odh-bucket-sa
    timeout: 600
