apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    modelFormat: vLLM
    opendatahub.io/connection-path: models/llama-32-3b-instruct
    opendatahub.io/connections: odh-bucket
    opendatahub.io/model-type: generative
    openshift.io/display-name: llama-32-3b-instruct
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: Standard
    serving.kserve.io/stop: "false"
  finalizers:
  - odh.inferenceservice.finalizers
  - inferenceservice.finalizers
  labels:
    opendatahub.io/dashboard: "true"
  name: llama-32-3b-instruct
  namespace: llama
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: RollingUpdate
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
      - --enable-chunked-prefill
      - --enable-auto-tool-choice
      - --tool-call-parser=llama3_json
      - --max-model-len=8192
      - --chat-template=/app/data/template/tool_chat_template_llama3.2_json.jinja
      env:
      - name: VLLM_CPU_KVCACHE_SPACE
        value: "14"
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "32"
          memory: 48Gi
        requests:
          cpu: "32"
          memory: 48Gi
      runtime: vllm-cpu-runtime
      storage:
        key: odh-bucket
        path: models/llama-32-3b-instruct
    serviceAccountName: odh-bucket-sa
    timeout: 600
