apiVersion: ogx.io/v1beta1
kind: OGXServer
metadata:
  name: ogxserver
spec:
  distribution:
    image: quay.io/rhoai/odh-ogx-core-rhel9:rhoai-3.5-ea.2
  network:
    port: 8321
  workload:
    overrides:
      env:
        - name: POSTGRES_HOST
          value: "postgres.llama.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "ogx"
        - name: POSTGRES_USER
          value: "ogx"
        - name: POSTGRES_PASSWORD
          value: "ogx"
        - name: VLLM_URL
          value: http://llama-32-3b-instruct-predictor.llama.svc.cluster.local:8080/v1
        - name: VLLM_TLS_VERIFY
          value:  "false"
        - name: VLLM_API_TOKEN
          value: "fake"
        - name: VLLM_MAX_TOKENS
          value: "80"
        - name: VLLM_EMBEDDING_URL
          value: http://granite-embeddings-predictor.llama.svc.cluster.local:8080/v1
        - name: ENABLE_PGVECTOR
          value: "pgvector"
        - name: PGVECTOR_PORT
          value: "5433"
        - name: PGVECTOR_DB
          value: "ogx_pgv"
        - name: PGVECTOR_USER
          value: "ogx_pgv"
        - name: PGVECTOR_PASSWORD
          value: "ogx_pgv"
        - name: PGVECTOR_HOST
          value: "10.20.180.75"
        - name: EMBEDDING_MODEL
          value: "granite-embeddings"
        - name: EMBEDDING_PROVIDER_MODEL_ID
          value: "granite-embeddings"
        - name: EMBEDDING_DIMENSION
          value: "768"
