apiVersion: ogx.io/v1beta1
kind: OGXServer
metadata:
  name: techmart-ogx
spec:
  distribution:
    image: quay.io/vahirwad/llama-stack-dist:3.5-ea2-ogx
  network:
    port: 8321
  workload:
    overrides:
      env:
        # PostgreSQL metadata store (from secret)
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD

        # Remote LLM configuration
        - name: VLLM_URL
          value: http://llama-32-3b-instruct-predictor.llama.svc.cluster.local:8080/v1
        - name: VLLM_TLS_VERIFY
          value:  "false"
        - name: VLLM_API_TOKEN
          value: "fake"
        - name: VLLM_MAX_TOKENS
          value: "80"

        # Remote Vector DB configuration
        - name: ENABLE_PGVECTOR
          value: "pgvector"
        - name: PGVECTOR_PORT
          value: "5433"
        - name: PGVECTOR_DB
          value: "ogx"
        - name: PGVECTOR_USER
          value: "ogx"
        - name: PGVECTOR_PASSWORD
          value: "ogx"
        - name: PGVECTOR_HOST
          value: "10.20.180.75"

        # Remote Embedding configuration 
        - name: VLLM_EMBEDDING_URL
          value: http://granite-embeddings-predictor.llama.svc.cluster.local:8080/v1
        - name: EMBEDDING_MODEL
          value: "granite-embeddings"
        - name: EMBEDDING_PROVIDER_MODEL_ID
          value: "granite-embeddings"
        - name: EMBEDDING_DIMENSION
          value: "768"
