apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: techmart-llama-stack
spec:
  replicas: 1
  server:
    podDisruptionBudget:
      minAvailable: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 1
    targetCPUUtilizationPercentage: 20
    targetMemoryUtilizationPercentage: 40
    containerSpec:
      env:
        # PostgreSQL metadata store (from secret)
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD

        # Inline embeddings (sentence-transformers)
        - name: ENABLE_SENTENCE_TRANSFORMERS
          value: "true"
        - name: EMBEDDING_PROVIDER
          value: "sentence-transformers"

        # Remote LLM configuration
        - name: INFERENCE_MODEL
          value: "llama-32-3b-instruct"
        - name: VLLM_URL
          value: http://llama-32-3b-instruct-predictor.llama.svc.cluster.local:8080/v1
        - name: VLLM_TLS_VERIFY
          value:  "false"
        - name: VLLM_API_TOKEN
          value: "fake"
        - name: VLLM_MAX_TOKENS
          value: "80"

        # Ragas inline configuration
        - name: TRUSTYAI_EMBEDDING_MODEL
          value: sentence-transformers/ibm-granite/granite-embedding-125m-english

        # Enable inline FAISS
        - name: ENABLE_FAISS
          value: "faiss"

        - name: LLAMA_STACK_PORT
          value: "8321"
      name: llama-stack
      port: 8321
    distribution:
      name: rh-dev
