---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: phi3
    opendatahub.io/connection-type-ref: s3
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: "true"
    networking.kserve.io/visibility: exposed
  name: phi3
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      args:
      - --disable-sliding-window
      resources:
        limits:
          cpu: "10"
          memory: 20Gi
        requests:
          cpu: "6"
          memory: 16Gi
      runtime: vllm-cpu-runtime
      storage:
        key: s3-creds
        path: models/phi-3-mini-4k-instruct
    timeout: 900
